### ISSUE TITLE
просьба добавить хоткей для вызова окна

### ISSUE THREAD

**Issue by deepdusky** [ivantsov/yandex-mail-notifier-firefox#10]
добрый день.
при случае пожалуйста добавьте хоткей для вызова окна.
очень бы хотелось, чтоб он был настраиваемым, так как это сделано в аддоне
gmail panel
( https://addons.mozilla.org/ru/firefox/addon/gmail-panel/?src=search )
спасибо.

**Comment by deepdusky** [comment]
и возможность задать в минутах периодичность проверки.

**Comment by ivantsov** [comment]
HotKey добавлен в новой версии расширения - https://github.com/ivantsov/yandex-mail-notifier.
