### ISSUE TITLE
Не актуально отображает количество не прочитанных.

### ISSUE THREAD

**Issue by MIKEk8** [ivantsov/yandex-mail-notifier-firefox#11]
Пожалуйста добавьте возможность ручной синхронизации. зачастую после прочтения остаётся счётчик. Также при работе на ноутбуке когда запускал браузер без интернета, а потом интернет подключил, то ваш плагин не подключился, и постоянно спамил что не авторизован.

**Comment by fanatid** [comment]
Пользуюсь веб интерфейсом от яндекс почты, тоже иногда остается счетчик новых писем после удаления/прочтения. Особенно наблюдалось когда интернет был только 3G (через модем). Поддержка почты не понимает проблемы (один раз отписались, что пофиксят, другой просто была обычная отписка). В общем не всё так однозначно.

**Comment by ivantsov** [comment]
Такой проблемы не должно возникать с новой версией - https://github.com/ivantsov/yandex-mail-notifier.
