### ISSUE TITLE
Несколько аккаунтов

### ISSUE THREAD

**Issue by HardDie** [ivantsov/yandex-mail-notifier-firefox#12]
У яндекс плагина есть возможность просматривать сразу несколько аккаунтов почты, в вашем расширении не хватает такой фичи, либо я просто не нашел

**Comment by ivantsov** [comment]
Данная фича не поддерживается на данный момент. Если вы хотите увидеть её в будущем, вы можете поддержать проект здесь - https://donorbox.org/alexander-ivantsov.
